learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register,name='register'),
    url(r'^user_login/$', views.user_login,name='user_login'),
    url(r'^special/',views.special,name='special'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views
#my creativity
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout,name='logout'),
    #url(r'^special/',views.special,name='special'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)

    #additional classes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User   # Importing system defined model from django Admin named "User"
from basic_app.models import UserProfileInfo    # Importing Developer defined model from django named "UserProfileInfo"

class UserForm(forms.ModelForm):
    password = forms.CharField(widget= forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm       # Import from Forms.py to views.py

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
#my extra creativity to retrive datas
from basic_app.models import UserProfileInfo
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    #user_output = UserProfileInfo.objects
    return render(request,'basic_app/index.html')

def special(request):
    return render(request,'basic_app/special.html')
#    return HttpResponse("<h1>You are logged in, Nice</h1>")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == "POST":

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user         # OneToOneField can be done with this line of code

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',{'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponseRedirect("Account is not active")
        else:
            print("Someone tried to login and failed")
            print("Username:{} and password:{}".format(username,password))
            return HttpResponse("Login Details are invalid!")
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-exapand lg navbar-static-top bg-danger">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'index' %}">ENRICH</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:special' %}">Profile</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Level 5 homepage</h1>
</div>
{% if user.is_authenticated %}
  <div class="jumbotron">
    <h2>Click on Profile to view info</h2>
  </div>

{% endif %}

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login!</h1>
    <h6>Are you a New User?<a href="{% url 'basic_app:register' %}"> Sign Up</a></h6>
    <form action="{% url 'basic_app:user_login' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username: </label>
      <input type="text" name="username" placeholder="Enter user_name" required><br><br>
      <label for="password">Password: </label>
      <input type="password" name="password" required><br><br>
      <input type="submit" class="btn btn-success" value="Login">
    </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank You for registering with Us!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data" method="POST">
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-success" name="" value="Register">
    </form>
  {% endif %}

</div>
{% endblock %}

learning_users/templates/basic_app/special.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

  <div class="jumbotron">
    <h1>Your Profile</h1>
    {% if user.is_authenticated %}

    <!--    <ul>
          <li>User Info:</li><br> -->

            <label>Profile Picture: </label><br>
            <img class="img-thumbnail" src="{{ user.userprofileinfo.profile_pic.url }}" height="240px" width="240px"><br><br>
            <p>Username: <strong>{{ user }}</strong></p><br>
            <p>Email: <strong>{{ user.email }}</strong></p><br>
            <p>portfolio_site: <strong>{{ user.userprofileinfo.portfolio_site }}</strong></p><br>


    <!--    </ul> -->

    {% endif %}
  </div>

{% endblock %}